class AlreadyExistExeption(Exception):
    pass

class FailureAuthenticationException(Exception):
    pass

class UserNotFoundException(Exception):
    pass
